
import java.awt.Color;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class menu_utama extends javax.swing.JFrame {
int x,y,xx,yy;

    /**
     * Creates new form menu_utama
     */
    public menu_utama() {
        initComponents();
//        User user = new User();
//        DP.add(user).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        UserPn = new javax.swing.JPanel();
        UserLb = new javax.swing.JLabel();
        SupirPn = new javax.swing.JPanel();
        SupirLb = new javax.swing.JLabel();
        KendaraanPn = new javax.swing.JPanel();
        KendaraanLb = new javax.swing.JLabel();
        PeminjamanPn = new javax.swing.JPanel();
        PeminjamanLb = new javax.swing.JLabel();
        PengembalianPn = new javax.swing.JPanel();
        PengembalianLb = new javax.swing.JLabel();
        LaporanPn = new javax.swing.JPanel();
        LaporanLb = new javax.swing.JLabel();
        InfoPn = new javax.swing.JPanel();
        InfoLb = new javax.swing.JLabel();
        DP = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/istockphoto-1290071290-612x612.jpg"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 138, 140));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel3.setText("SAWARGI RENT CAR");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/maps.png"))); // NOI18N
        jLabel4.setText("Komplek Permata Biru AL 146, Cinunuk, Cileunyi, Bandung, Jawa Barat 40441");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/whatsapp.png"))); // NOI18N
        jLabel5.setText("+6285101877356");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1100, 140));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 11)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/close.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        UserPn.setBackground(new java.awt.Color(51, 153, 255));
        UserPn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UserPn.setPreferredSize(new java.awt.Dimension(170, 40));
        UserPn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserPnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UserPnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UserPnMouseExited(evt);
            }
        });
        UserPn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserLb.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        UserLb.setForeground(new java.awt.Color(255, 255, 255));
        UserLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/user.png"))); // NOI18N
        UserLb.setText("USER");
        UserLb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UserLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserLbMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UserLbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UserLbMouseExited(evt);
            }
        });
        UserPn.add(UserLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 0, 95, 40));

        SupirPn.setBackground(new java.awt.Color(51, 153, 255));
        SupirPn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SupirPn.setPreferredSize(new java.awt.Dimension(170, 40));
        SupirPn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupirPnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SupirPnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SupirPnMouseExited(evt);
            }
        });
        SupirPn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SupirLb.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        SupirLb.setForeground(new java.awt.Color(255, 255, 255));
        SupirLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/race.png"))); // NOI18N
        SupirLb.setText("SUPIR");
        SupirLb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SupirLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupirLbMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SupirLbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SupirLbMouseExited(evt);
            }
        });
        SupirPn.add(SupirLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 95, 40));

        KendaraanPn.setBackground(new java.awt.Color(51, 153, 255));
        KendaraanPn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        KendaraanPn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KendaraanPnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                KendaraanPnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                KendaraanPnMouseExited(evt);
            }
        });
        KendaraanPn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        KendaraanLb.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        KendaraanLb.setForeground(new java.awt.Color(255, 255, 255));
        KendaraanLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/garage.png"))); // NOI18N
        KendaraanLb.setText("KENDARAAN");
        KendaraanLb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        KendaraanLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KendaraanLbMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                KendaraanLbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                KendaraanLbMouseExited(evt);
            }
        });
        KendaraanPn.add(KendaraanLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 0, -1, 40));

        PeminjamanPn.setBackground(new java.awt.Color(51, 153, 255));
        PeminjamanPn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PeminjamanPn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PeminjamanPnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PeminjamanPnMouseExited(evt);
            }
        });
        PeminjamanPn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PeminjamanLb.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        PeminjamanLb.setForeground(new java.awt.Color(255, 255, 255));
        PeminjamanLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/tenant.png"))); // NOI18N
        PeminjamanLb.setText("PEMINJAMAN");
        PeminjamanLb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PeminjamanLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PeminjamanLbMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PeminjamanLbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PeminjamanLbMouseExited(evt);
            }
        });
        PeminjamanPn.add(PeminjamanLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 0, -1, 40));

        PengembalianPn.setBackground(new java.awt.Color(51, 153, 255));
        PengembalianPn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PengembalianPn.setMinimumSize(new java.awt.Dimension(170, 40));
        PengembalianPn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PengembalianPnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PengembalianPnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PengembalianPnMouseExited(evt);
            }
        });
        PengembalianPn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PengembalianLb.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        PengembalianLb.setForeground(new java.awt.Color(255, 255, 255));
        PengembalianLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/car.png"))); // NOI18N
        PengembalianLb.setText("PENGEMBALIAN");
        PengembalianLb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PengembalianLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PengembalianLbMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PengembalianLbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PengembalianLbMouseExited(evt);
            }
        });
        PengembalianPn.add(PengembalianLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 40));

        LaporanPn.setBackground(new java.awt.Color(51, 153, 255));
        LaporanPn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LaporanPn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LaporanPnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LaporanPnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LaporanPnMouseExited(evt);
            }
        });
        LaporanPn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LaporanLb.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        LaporanLb.setForeground(new java.awt.Color(255, 255, 255));
        LaporanLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/analytics.png"))); // NOI18N
        LaporanLb.setText("LAPORAN");
        LaporanLb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LaporanLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LaporanLbMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LaporanLbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LaporanLbMouseExited(evt);
            }
        });
        LaporanPn.add(LaporanLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 40));

        InfoPn.setBackground(new java.awt.Color(51, 153, 255));
        InfoPn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InfoPn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InfoPnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InfoPnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InfoPnMouseExited(evt);
            }
        });
        InfoPn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InfoLb.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        InfoLb.setForeground(new java.awt.Color(255, 255, 255));
        InfoLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/info.png"))); // NOI18N
        InfoLb.setText("INFO");
        InfoLb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InfoLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InfoLbMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InfoLbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InfoLbMouseExited(evt);
            }
        });
        InfoPn.add(InfoLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 120, 40));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(UserPn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(SupirPn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(KendaraanPn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PeminjamanPn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PengembalianPn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(LaporanPn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(InfoPn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(UserPn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(KendaraanPn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LaporanPn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SupirPn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PeminjamanPn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PengembalianPn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(InfoPn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1100, 40));

        DP.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout DPLayout = new javax.swing.GroupLayout(DP);
        DP.setLayout(DPLayout);
        DPLayout.setHorizontalGroup(
            DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        DPLayout.setVerticalGroup(
            DPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        getContentPane().add(DP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 1100, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    System.exit(0);       // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
    x= evt.getX();
    y=evt.getY();    // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
    xx = evt.getXOnScreen();
    yy = evt.getYOnScreen();
    this.setLocation(xx-x,yy-y);// TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseDragged

    private void UserPnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserPnMouseClicked
        DP.removeAll();
        User user= new User();
        DP.add(user).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_UserPnMouseClicked

    private void SupirPnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupirPnMouseClicked
        DP.removeAll();
        Supir supir= new Supir();
        DP.add(supir).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_SupirPnMouseClicked

    private void KendaraanPnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KendaraanPnMouseClicked
        DP.removeAll();
        Kendaraan kendaraan= new Kendaraan();
        DP.add(kendaraan).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_KendaraanPnMouseClicked

    private void PengembalianPnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PengembalianPnMouseClicked
        DP.removeAll();
        Pengembalian kembali= new Pengembalian();
        DP.add(kembali).setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_PengembalianPnMouseClicked

    private void UserLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserLbMouseClicked
        DP.removeAll();
        User user= new User();
        DP.add(user).setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_UserLbMouseClicked

    private void SupirLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupirLbMouseClicked
        DP.removeAll();
        Supir supir= new Supir();
        DP.add(supir).setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_SupirLbMouseClicked

    private void KendaraanLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KendaraanLbMouseClicked
        DP.removeAll();
        Kendaraan kendaraan= new Kendaraan();
        DP.add(kendaraan).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_KendaraanLbMouseClicked

    private void PengembalianLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PengembalianLbMouseClicked
        DP.removeAll();
        Pengembalian kembali= new Pengembalian();
        DP.add(kembali).setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_PengembalianLbMouseClicked

    private void PeminjamanLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PeminjamanLbMouseClicked
        DP.removeAll();
        Penyewa sewa= new Penyewa();
        DP.add(sewa).setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_PeminjamanLbMouseClicked

    private void UserLbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserLbMouseEntered
        UserPn.setBackground(new Color(102,153,255));        // TODO add your handling code here:
    }//GEN-LAST:event_UserLbMouseEntered

    private void UserPnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserPnMouseEntered
        UserPn.setBackground(new Color(102,153,255));  // TODO add your handling code here:
    }//GEN-LAST:event_UserPnMouseEntered

    private void UserPnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserPnMouseExited
        UserPn.setBackground(new Color(51,153,255));          // TODO add your handling code here:
    }//GEN-LAST:event_UserPnMouseExited

    private void UserLbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserLbMouseExited
        UserPn.setBackground(new Color(51,153,255));    // TODO add your handling code here:
    }//GEN-LAST:event_UserLbMouseExited

    private void SupirPnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupirPnMouseEntered
        SupirPn.setBackground(new Color(102,153,255));   // TODO add your handling code here:
    }//GEN-LAST:event_SupirPnMouseEntered

    private void SupirPnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupirPnMouseExited
       SupirPn.setBackground(new Color(51,153,255)); // TODO add your handling code here:
    }//GEN-LAST:event_SupirPnMouseExited

    private void SupirLbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupirLbMouseEntered
        SupirPn.setBackground(new Color(102,153,255));// TODO add your handling code here:
    }//GEN-LAST:event_SupirLbMouseEntered

    private void SupirLbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupirLbMouseExited
        SupirPn.setBackground(new Color(51,153,255));// TODO add your handling code here:
    }//GEN-LAST:event_SupirLbMouseExited

    private void KendaraanLbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KendaraanLbMouseExited
        KendaraanPn.setBackground(new Color(51,153,255));// TODO add your handling code here:
    }//GEN-LAST:event_KendaraanLbMouseExited

    private void KendaraanLbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KendaraanLbMouseEntered
        KendaraanPn.setBackground(new Color(102,153,255));// TODO add your handling code here:
    }//GEN-LAST:event_KendaraanLbMouseEntered

    private void KendaraanPnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KendaraanPnMouseEntered
        KendaraanPn.setBackground(new Color(102,153,255));// TODO add your handling code here:
    }//GEN-LAST:event_KendaraanPnMouseEntered

    private void KendaraanPnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KendaraanPnMouseExited
        KendaraanPn.setBackground(new Color(51,153,255));// TODO add your handling code here:
    }//GEN-LAST:event_KendaraanPnMouseExited

    private void PeminjamanPnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PeminjamanPnMouseEntered
        PeminjamanPn.setBackground(new Color(102,153,255));// TODO add your handling code here:
    }//GEN-LAST:event_PeminjamanPnMouseEntered

    private void PeminjamanPnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PeminjamanPnMouseExited
        PeminjamanPn.setBackground(new Color(51,153,255));// TODO add your handling code here:
    }//GEN-LAST:event_PeminjamanPnMouseExited

    private void PengembalianPnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PengembalianPnMouseEntered
        PengembalianPn.setBackground(new Color(102,153,255));// TODO add your handling code here:
    }//GEN-LAST:event_PengembalianPnMouseEntered

    private void PengembalianPnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PengembalianPnMouseExited
        PengembalianPn.setBackground(new Color(51,153,255));// TODO add your handling code here:
    }//GEN-LAST:event_PengembalianPnMouseExited

    private void LaporanPnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LaporanPnMouseEntered
        LaporanPn.setBackground(new Color(102,153,255));// TODO add your handling code here:
    }//GEN-LAST:event_LaporanPnMouseEntered

    private void LaporanPnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LaporanPnMouseExited
        LaporanPn.setBackground(new Color(51,153,255));// TODO add your handling code here:
    }//GEN-LAST:event_LaporanPnMouseExited

    private void InfoPnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InfoPnMouseEntered
    InfoPn.setBackground(new Color(102,153,255));// TODO add your handling code here:
    }//GEN-LAST:event_InfoPnMouseEntered

    private void InfoPnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InfoPnMouseExited
    InfoPn.setBackground(new Color(51,153,255));        // TODO add your handling code here:
    }//GEN-LAST:event_InfoPnMouseExited

    private void PengembalianLbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PengembalianLbMouseExited
    PengembalianPn.setBackground(new Color(51,153,255));    // TODO add your handling code here:
    }//GEN-LAST:event_PengembalianLbMouseExited

    private void PengembalianLbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PengembalianLbMouseEntered
    PengembalianPn.setBackground(new Color(102,153,255));        // TODO add your handling code here:
    }//GEN-LAST:event_PengembalianLbMouseEntered

    private void LaporanLbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LaporanLbMouseEntered
    LaporanPn.setBackground(new Color(102,153,255));    // TODO add your handling code here:
    }//GEN-LAST:event_LaporanLbMouseEntered

    private void LaporanLbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LaporanLbMouseExited
    LaporanPn.setBackground(new Color(51,153,255));    // TODO add your handling code here:
    }//GEN-LAST:event_LaporanLbMouseExited

    private void InfoLbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InfoLbMouseEntered
     InfoPn.setBackground(new Color(102,153,255));   // TODO add your handling code here:
    }//GEN-LAST:event_InfoLbMouseEntered

    private void InfoLbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InfoLbMouseExited
    InfoPn.setBackground(new Color(51,153,255));        // TODO add your handling code here:
    }//GEN-LAST:event_InfoLbMouseExited

    private void PeminjamanLbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PeminjamanLbMouseExited
    PeminjamanPn.setBackground(new Color(51,153,255));    // TODO add your handling code here:
    }//GEN-LAST:event_PeminjamanLbMouseExited

    private void PeminjamanLbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PeminjamanLbMouseEntered
    PeminjamanPn.setBackground(new Color(102,153,255));        // TODO add your handling code here:
    }//GEN-LAST:event_PeminjamanLbMouseEntered

    private void InfoPnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InfoPnMouseClicked
        DP.removeAll();
        Info info= new Info();
        DP.add(info).setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_InfoPnMouseClicked

    private void InfoLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InfoLbMouseClicked
        DP.removeAll();
        Info info= new Info();
        DP.add(info).setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_InfoLbMouseClicked

    private void LaporanLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LaporanLbMouseClicked
        DP.removeAll();
        Laporan lapor= new Laporan();
        DP.add(lapor).setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_LaporanLbMouseClicked

    private void LaporanPnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LaporanPnMouseClicked
    DP.removeAll();
        Laporan lapor= new Laporan();
        DP.add(lapor).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_LaporanPnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane DP;
    private javax.swing.JLabel InfoLb;
    private javax.swing.JPanel InfoPn;
    private javax.swing.JLabel KendaraanLb;
    private javax.swing.JPanel KendaraanPn;
    private javax.swing.JLabel LaporanLb;
    private javax.swing.JPanel LaporanPn;
    private javax.swing.JLabel PeminjamanLb;
    private javax.swing.JPanel PeminjamanPn;
    private javax.swing.JLabel PengembalianLb;
    private javax.swing.JPanel PengembalianPn;
    private javax.swing.JLabel SupirLb;
    private javax.swing.JPanel SupirPn;
    private javax.swing.JLabel UserLb;
    private javax.swing.JPanel UserPn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
