
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class Penyewa extends javax.swing.JInternalFrame {
Connection koneksi;
PreparedStatement pst;
    /**
     * Creates new form Penyewa
     */
    public Penyewa() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        koneksi = DatabaseConnection.getKoneksi("localhost", "3306", "root", "", "sawargi_rent_car");
        setTitle("Penyewa");
        kode();
    }
    private void kode() {
        try {
            Statement s = koneksi.createStatement();

            String sql = "SELECT * FROM `tb_penyewa` ORDER by `No_ID` desc";
            ResultSet r = s.executeQuery(sql);

            if (r.next()) {
                String no = r.getString("No_ID").substring(2);
                String AN = "" + (Integer.parseInt(no) + 1);
                String Nol = "";

                if (AN.length() == 1) {
                    Nol = "00";
                } else if (AN.length() == 2) {
                    Nol = "0";
                } else if (AN.length() == 3) {
                    Nol = "";
                } 

                no_id.setText("KT" + Nol + AN);
            } else {
                no_id.setText("KT001");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        no_id = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Nama_TF = new javax.swing.JTextField();
        Nama_Lbl = new javax.swing.JLabel();
        NIK_TF = new javax.swing.JTextField();
        NIK_Lbl = new javax.swing.JLabel();
        Telp_TF = new javax.swing.JTextField();
        Telp_Lbl = new javax.swing.JLabel();
        Alamat_Lbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Alamat_TA = new javax.swing.JTextArea();
        Clear_Btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Next_Btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        no_id.setText("jTextField1");

        setPreferredSize(new java.awt.Dimension(1100, 640));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PENYEWA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Nama_TF.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        Nama_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nama_TFActionPerformed(evt);
            }
        });

        Nama_Lbl.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        Nama_Lbl.setText("NAMA :");

        NIK_TF.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        NIK_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NIK_TFActionPerformed(evt);
            }
        });
        NIK_TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NIK_TFKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NIK_TFKeyReleased(evt);
            }
        });

        NIK_Lbl.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        NIK_Lbl.setText("NIK :");

        Telp_TF.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        Telp_Lbl.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        Telp_Lbl.setText("TELP :");

        Alamat_Lbl.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        Alamat_Lbl.setText("ALAMAT :");

        Alamat_TA.setColumns(20);
        Alamat_TA.setRows(5);
        jScrollPane1.setViewportView(Alamat_TA);

        Clear_Btn.setBackground(new java.awt.Color(255, 255, 255));
        Clear_Btn.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        Clear_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/eraser.png"))); // NOI18N
        Clear_Btn.setText("CLEAR");
        Clear_Btn.setBorderPainted(false);
        Clear_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Clear_Btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Clear_Btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Clear_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_BtnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/follow.png"))); // NOI18N

        Next_Btn.setBackground(new java.awt.Color(255, 255, 255));
        Next_Btn.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        Next_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/fast-forward.png"))); // NOI18N
        Next_Btn.setText("NEXT");
        Next_Btn.setBorderPainted(false);
        Next_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Next_Btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Next_Btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Next_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_BtnActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 45));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/pencil.png"))); // NOI18N
        jButton1.setText("EDIT");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NIK_Lbl)
                        .addGap(71, 71, 71)
                        .addComponent(NIK_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Nama_Lbl)
                        .addGap(52, 52, 52)
                        .addComponent(Nama_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Telp_Lbl)
                        .addGap(64, 64, 64)
                        .addComponent(Telp_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Alamat_Lbl)
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(Clear_Btn)
                        .addGap(51, 51, 51)
                        .addComponent(jButton1)
                        .addGap(51, 51, 51)
                        .addComponent(Next_Btn)))
                .addGap(0, 227, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1084, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NIK_Lbl)
                            .addComponent(NIK_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nama_Lbl)
                            .addComponent(Nama_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Telp_Lbl)
                            .addComponent(Telp_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Alamat_Lbl)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Clear_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(Next_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NIK_TFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NIK_TFKeyPressed
        Nama_TF.setText(null);
        Telp_TF.setText(null);
        Alamat_TA.setText(null);// TODO add your handling code here:
    }//GEN-LAST:event_NIK_TFKeyPressed

    private void NIK_TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NIK_TFKeyReleased
        try {
            Statement stmt = koneksi.createStatement();
            String sql = "SELECT * FROM tb_penyewa WHERE Nik='"+NIK_TF.getText()+"'";
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                Nama_TF.setText(rs.getString("Nama"));
                Telp_TF.setText(rs.getString("Telp"));
                Alamat_TA.setText(rs.getString("Alamat"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Member Tidak Ditemukan" + e.getMessage(), "Pesan", JOptionPane.ERROR_MESSAGE);
        }    // TODO add your handling code here:
    }//GEN-LAST:event_NIK_TFKeyReleased

    private void Next_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_BtnActionPerformed
        if (Nama_TF.getText().isEmpty() || Telp_TF.getText().isEmpty() || NIK_TF.getText().isEmpty ()|| Alamat_TA.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan data!");
        }else{
            String nama = Nama_TF.getText(); // TODO add your handling code here:
            String telp = Telp_TF.getText();
            String nik = NIK_TF.getText();
            String alamat = Alamat_TA.getText();
            Peminjaman pinjam = new Peminjaman(nama, telp, alamat, nik);           
            menu_utama.DP.removeAll();
            pinjam.setVisible(true);
            menu_utama.DP.add(pinjam).setVisible(true);
            this.dispose();
        }try {
            String sql = "insert into tb_penyewa (No_ID,Nama,Nik,Telp,Alamat) value (?,?,?,?,?)";
            pst = koneksi.prepareStatement(sql);
            pst.setString(1, no_id.getText());
            pst.setString(2, Nama_TF.getText());
            pst.setString(3, NIK_TF.getText());
            pst.setString(4, Telp_TF.getText());
            pst.setString(5, Alamat_TA.getText());
            pst.executeUpdate();
        }catch (SQLException e){
        }
    }//GEN-LAST:event_Next_BtnActionPerformed

    private void Clear_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_BtnActionPerformed
        Nama_TF.setText("");
        Telp_TF.setText("");
        NIK_TF.setText("");
        Alamat_TA.setText("");    // TODO add your handling code here:
    }//GEN-LAST:event_Clear_BtnActionPerformed

    private void Nama_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nama_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nama_TFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        menu_utama.DP.removeAll();
        TPenyewa Tsewa= new TPenyewa();
        menu_utama.DP.add(Tsewa).setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NIK_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NIK_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NIK_TFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat_Lbl;
    private javax.swing.JTextArea Alamat_TA;
    private javax.swing.JButton Clear_Btn;
    private javax.swing.JLabel NIK_Lbl;
    private javax.swing.JTextField NIK_TF;
    private javax.swing.JLabel Nama_Lbl;
    private javax.swing.JTextField Nama_TF;
    private javax.swing.JButton Next_Btn;
    private javax.swing.JLabel Telp_Lbl;
    private javax.swing.JTextField Telp_TF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField no_id;
    // End of variables declaration//GEN-END:variables
}
