
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class TPenyewa extends javax.swing.JInternalFrame {
Connection koneksi;
PreparedStatement pst;
    /**
     * Creates new form TPenyewa
     */
    public TPenyewa() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        initComponents();
        koneksi = DatabaseConnection.getKoneksi("localhost","3306","root","","sawargi_rent_car");
        showData();
        kode();
        update();
    }
    DefaultTableModel dtm;
    public void showData(){
        String[] kolom={"NO_ID","NIK","NAMA","TELP","ALAMAT"};
 
        dtm = new DefaultTableModel(null,kolom);
        try{
            Statement stmt = koneksi.createStatement();
            String query = "SELECT * FROM tb_penyewa";
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next()){
                String no_id = rs.getString("No_ID");
                String nama = rs.getString("Nik");
                String nik = rs.getString("Nama");
                String telp = rs.getString("Telp");
                String alamat = rs.getString("Alamat");
                
                dtm.addRow(new String[]{no_id,nama,nik,telp,alamat});
            }
        }
        catch (SQLException ex) {
            ex.printStackTrace();
        }
        tb_penyewa.setModel(dtm);
    }
    
    public void KosongkanForm() {
        Nama.setText(null);
        NIK.setText(null);
        id.setText(null);
        Telp.setText(null);
        Alamat.setText(null);
    }

    private void update(){
    try{
        String sql ="select * from tb_penyewa";
        pst=koneksi.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();
        tb_penyewa.setModel(DbUtils.resultSetToTableModel(rs));
    }catch (Exception ex)
    { }
    showData();
  }
    
    private void kode() {
        try {
            Statement s = koneksi.createStatement();

            String sql = "SELECT * FROM `tb_penyewa` ORDER by `No_ID` desc";
            ResultSet r = s.executeQuery(sql);

            if (r.next()) {
                String noo = r.getString("No_ID").substring(2);
                String ANN = "" + (Integer.parseInt(noo) + 1);
                String Noll = "";

                if (ANN.length() == 1) {
                    Noll = "00";
                } else if (ANN.length() == 2) {
                    Noll = "0";
                } else if (ANN.length() == 3) {
                    Noll = "";
                } 

                id.setText("KP" + Noll + ANN);
            } else {
                id.setText("KP001");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        NIK = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Telp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Alamat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_penyewa = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1100, 640));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("MASTER PENYEWA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(460, 460, 460)
                .addComponent(jLabel10)
                .addContainerGap(458, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 45));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 45));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 1084, 30));

        id.setEditable(false);
        id.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idKeyReleased(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 131, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        jLabel4.setText("NO ID :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 40, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        jLabel2.setText("NIK :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        Nama.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        jPanel1.add(Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 131, -1));

        NIK.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        jPanel1.add(NIK, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 131, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        jLabel6.setText("TELP :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        Telp.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        jPanel1.add(Telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 131, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        jLabel1.setText("NAMA :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        btnsave.setBackground(new java.awt.Color(255, 255, 255));
        btnsave.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/add.png"))); // NOI18N
        btnsave.setText("SAVE");
        btnsave.setBorderPainted(false);
        btnsave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 69, -1));

        btnedit.setBackground(new java.awt.Color(255, 255, 255));
        btnedit.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/pencil.png"))); // NOI18N
        btnedit.setText("EDIT");
        btnedit.setBorderPainted(false);
        btnedit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnedit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnedit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel1.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 69, -1));

        btndelete.setBackground(new java.awt.Color(255, 255, 255));
        btndelete.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/delete.png"))); // NOI18N
        btndelete.setText("DELETE");
        btndelete.setBorderPainted(false);
        btndelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        jLabel7.setText("ALAMAT :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        Alamat.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        jPanel1.add(Alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 131, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/USERR.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        tb_penyewa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_penyewa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_penyewaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_penyewa);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 1000, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyReleased
        kode();        // TODO add your handling code here:
    }//GEN-LAST:event_idKeyReleased

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        try{
            String sql = " INSERT INTO tb_penyewa VALUES('" + id.getText() + "','"
            + NIK.getText() + "','"
            + Nama.getText() + "','"
            + Telp.getText() + "','"
            + Alamat.getText() + "')";
            pst = koneksi.prepareStatement(sql);
            pst.execute();
            showData();
            JOptionPane.showMessageDialog(null, "Proses Simpan Berhasil");
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Masukkan Data Dengan Benar!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        KosongkanForm();
        update();
        kode();
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "UPDATE `tb_penyewa` SET `Nik`='" + NIK.getText()
            + "',`Nama`='" + Nama.getText()
            + "',`Telp`='" + Telp.getText()
            + "',`Alamat`='" + Alamat.getText()
            + "' WHERE `No_ID`= '" + id.getText() + "'";

            pst = koneksi.prepareStatement (sql);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Proses Edit Berhasil");
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Masukkan Data Dengan Benar!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        KosongkanForm();
        showData();
        kode();
    }//GEN-LAST:event_btneditActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        try {

            String sql ="DELETE FROM `tb_penyewa` WHERE `No_ID`='"+id.getText()+"'";
            pst=koneksi.prepareStatement(sql);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "berhasil di hapus");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "gagal di hapus");
        }
        KosongkanForm();
        showData();
        kode();
    }//GEN-LAST:event_btndeleteActionPerformed

    private void tb_penyewaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_penyewaMouseClicked
        id.setText(String.valueOf( tb_penyewa.getValueAt(tb_penyewa.getSelectedRow(),0)));
        NIK.setText(String.valueOf( tb_penyewa.getValueAt(tb_penyewa.getSelectedRow(),1)));
        Nama.setText(String.valueOf(tb_penyewa.getValueAt(tb_penyewa.getSelectedRow(),2)));
        Telp.setText(String.valueOf( tb_penyewa.getValueAt(tb_penyewa.getSelectedRow(),3)));
        Alamat.setText(String.valueOf( tb_penyewa.getValueAt(tb_penyewa.getSelectedRow(),4)));
        
                // TODO add your handling code here:
    }//GEN-LAST:event_tb_penyewaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alamat;
    private javax.swing.JTextField NIK;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Telp;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnsave;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_penyewa;
    // End of variables declaration//GEN-END:variables
}
